### ISSUE TITLE
Crash on i486 tablet

### ISSUE THREAD

**Issue by a-dekker** [rinigus/osmscout-server#107]
Hi Rinigus,
Read your call for help regarding crashes on the Jolla Tablet (SailfishOS 2.1.0.10) on TMO. I'm was not running osmscout-server on my tablet, but did an attempt to install it. It indeed crashes with an illegal operation right away.

Could you compile it with the latest SDK? Already tried it, but I am missing all kind of osmscout devel packages. Some issues are resolved just by compiling with the new SDK.

And if you want gdb debug info, I think we need a rpm debug version, not the regular rpm.

**Comment by rinigus** [comment]
Thank you very much for opening an issue!

Indeed, compilation of OSM Scout Server is a major undertaking - you have to compile and install a large range of the libraries. I have made packaging scripts for them, but should probably write a script to automate the compilation and installation of them. The packaging scripts are at https://github.com/rinigus?tab=repositories if there is some interest to work on it in future.

As for compilation with the latest SDK (EA). I guess I should try, but it would take some time. I would prefer to keep my current development PC with the stable SDK to avoid any issues with SFOS 2.0.x which I use myself. So, I would have to find another PC to test compilation with newer SDK.

I do wonder if we have any tablet users on 2.0.x and whether this crash is only on 2.1.0.x. Probably most moved to EA, unfortunately.

**Comment by rinigus** [comment]
@a-dekker, I can also upload other RPMs that were generated during compilation which should contain debug symbols as well.

As for changes in 0.8.0 compared to 0.7.5: a new library is linked (kyoto cabinet), libosmscout is updated, geocoder-nlp is updated, command line parsing is added.

0.8.0 runs fine on 2.0.x SDK emulator.

**Comment by a-dekker** [comment]
FYI: just tried, harbour-osmscout-server-0.7.5-1.i486 works fine on SailfishOS 2.1.0.10. So it must be some regression in the latest version.

**Comment by rinigus** [comment]
OK, I'll try to make some versions with parts of the code commented out. The biggest newcomer is probably kyotocabinet library. Maybe it managed to find some "optimal" settings during configuration. I'll try to make a build without it and let's see if this would work. I could do that late tonight, in ~10 hours from now.

**Comment by rinigus** [comment]
Issue could be related to http://www.merproject.org/logs/%23sailfishos/%23sailfishos.2014-04-27.log.html#t2014-04-27T10:25:54 . Would have to check BIOS settings and recompile all newer libs.

**Comment by rinigus** [comment]
As a part of a check whether some new library has caused the crash, I compiled a version that has Kyoto Cabinet commented out. **The functionality is broken**, but I wonder whether it starts. The packages are available at 

http://osmscoutserver-test.e24files.com/harbour-osmscout-server-0.8.0-1.i486.rpm

Looking forward to hear whether this RPM starts the server or fails with the same illegal instruction.

Debuginfo is probably what's needed in addition to regular RPM above to check with gdb: http://osmscoutserver-test.e24files.com/harbour-osmscout-server-debuginfo-0.8.0-1.i486.rpm

**Comment by a-dekker** [comment]
It starts okay.

**Comment by rinigus** [comment]
excellent ! I will try to recompile kyoto cabinet later tonight and see if I can catch some strange CPU optimization options that cause it.

**Comment by rinigus** [comment]
Would you mind to try a new build, http://osmscoutserver-test.e24files.com/harbour-osmscout-server-0.8.0-1.i486.rpm ? This should have full functionality with the recompiled Kyoto Cabinet

**Comment by a-dekker** [comment]
And... it doesn't crash anymore. Will do some test, but looks fine at first glance.

**Comment by rinigus** [comment]
Thank you very much! So, the bug was in configuration script that used -march=native and got through VM environment. I'll fix it in kyoto cabinet packaging scripts.

**Comment by rinigus** [comment]
I have just replaced i486 0.8.0 RPM in OpenRepos with the fixed release version. I presume that it should be OK now. Please reopen an issue if something is still wrong

**Comment by rinigus** [comment]
@a-dekker - thank you very much for your help!!!
