### ISSUE TITLE
Labels are sometimes cut

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#15]
see if there are more options that we can enable to get labels between tiles drawn without breaks.

**Comment by Karry** [comment]
It is usual problem when you render map to tiles. Label rendering is little bit nondeterministic. When you want to improve results, you have to increase area for data loading and setup `osmscout::MapParameter::SetDropNotVisiblePointLabels` to false. But it is too expensive for low zoom. This is why I disable it for zoom levels >=14.

I plan to review current label rendering code, but it is too low on my todo list :)

**Comment by rinigus** [comment]
I used the same code with if z>=14 and later kept it always enabled (set to false):

https://github.com/rinigus/osmscout-server/blob/master/src/dbmaster_map.cpp#L118

Now how do I increase the area for data loading and setup? If I know how to do it, I can let the user to choose whether (s)he wants to have more accurate labels or faster rendering. Taking into account that the tiles are cached by clients, it maybe OK for user to get the more accurate tiles and wait on the first rendering.

**Comment by rinigus** [comment]
closing after merge of @Karry PR
