### ISSUE TITLE
Crashes on Jolla Tablet

### ISSUE THREAD

**Issue by a-dekker** [rinigus/osmscout-server#155]
As I wanted to see how the memory use was on the 2GB Jolla tablet, I decided to to some searching and navigating.
To my surprise, it was a total no-go. Seconds after searching in Poor Maps, the memory use of harbour-scouts-server jumps to 1GB and lowmemorykiller kicks in. It does not matter if I use Valhalla or disable it.

Did something change recently for i486, or is something wrong with my config?

**Comment by rinigus** [comment]
I am not testing i486 at all - don't own any device allowing me to do that. Would be interesting to know though what could be the cause of it. On ARM (mako and onyx) all runs perfectly with 2 or 3GB RAM. 

Probably you can't even test with older versions much since the maps were updated as well. I'll try to run it in emulator environment and see if I can reproduce the issue.

Which version of SFOS do you have on the tablet? 2.1.0.x?

**Comment by a-dekker** [comment]
I have installed 2.1.0.11, the most recent release.

**Comment by rinigus** [comment]
What happens if you choose to use libosmscout for all backends (Settings and disable Mapnik/Geocoder-NLP/Valhalla)? Does it crash then as well?

BTW, the crash that you observed, was it after Search or Browsing map? If Search, did you limit the number of used languages in Geocoder-NLP?

**Comment by rinigus** [comment]
On emulator, it seems to be working, as much as I tested in this limited time.

**Comment by a-dekker** [comment]
Disabling Mapnik/Goecoder NLP/Valhalla makes it find a location without any issue.
The crashes where during a search.

**Comment by rinigus** [comment]
OK, if the crashes were during the search, maybe libpostal was loading all languages? Or did you select the languages to limit parsing to them? In Settings/Geocoder-NLP/Languages?

**Comment by a-dekker** [comment]
The (default?) all languages was selected (although none where selected in the list).
Now I just selected one language (as I have on my Jolla 1) and that seems to solve it!

**Comment by a-dekker** [comment]
So it was a config issue after all. Thanks for the guidance, I'll close the issue.

**Comment by rinigus** [comment]
Welcome ! I would have to work on defaults and warn users about selected languages . It was  planned in near future.
