### ISSUE TITLE
POI search near a reference position with large radius biased towards more distance results

### ISSUE THREAD

**Issue by M4rtinK** [rinigus/osmscout-server#161]
Looks like local search with a bigger radius returns more distant results, even if there are closer results available, examples:

`http://localhost:8553/v1/guide?lng=16.6&lat=49.2&query=Restaurant&limit=32&radius=10000`

Closest result is 1 km distant.

`http://localhost:8553/v1/guide?query=Restaurant&radius=1000&lat=49.2&lng=16.6&limit=32`

Closest result is 157 m distant.

It almost looks like if the result number limiting code ordered results by distance - farthest first - and then picked first n results & returned those.

OSM Scout Server version: 0.12.0-1
Map: Czech Republic
NLP: ON
NLP language: cs, en
search all available maps: ON (maps of Czech Republic, Austria, Italy (Centro) and Japan are installed)
use primitive parser: ON

**Comment by rinigus** [comment]
I will look into it, probably towards the end of the week. It is probably just stopping the search as soon as the number of requested POIs has been reached. We can try to let it search further and see if it will be not too slow.

**Comment by rinigus** [comment]
The issue should be fixed now, please reopen if its not true. I'll include the fix in the next point release
