### ISSUE TITLE
Add English names if available

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#163]
To assist in the countries with non-Latin alphabet,  we need to import and support English language names. Probably, should limit to English only since it would probably increase corresponding databases.

What has to be adjusted:

* Mapnik import
* Mapnik styles
* Geocoder-NLP import

Issue is related to https://github.com/M4rtinK/modrana/issues/201

**Comment by rinigus** [comment]
geocoder-nlp : done in terms of English support

**Comment by rinigus** [comment]
@M4rtinK, getting there ... 
![test](https://user-images.githubusercontent.com/15706605/28239492-f4d37b44-6975-11e7-80c7-47f626cce37c.png)

**Comment by M4rtinK** [comment]
Cool! :)
BTW, I'm using modRana quite a lot for general navigation (were are we now, how to get back to our hostel, etc.) and marking up interesting points, while we generally use online tools to look up public transport routes (the jaanese public transport network is very comrehensive). And so far the modRana & OSM Scout Server combo proved to be really robust! :)
