### ISSUE TITLE
Check if we can extend location to include other features

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#17]
An example: Erottaja, Helsinki fails to find a bus stop. See what's in location database by default and if it is feasible to extend.

**Comment by Karry** [comment]
Where can I found code that you are using for search? I was surprised recently that bus and tram stops are not tagged as POI, it may be reason for your problem...

**Comment by rinigus** [comment]
@Karry , morning! The function that is called by HTTP parser is 

https://github.com/rinigus/osmscout-server/blob/master/src/dbmaster_search.cpp#L230

In general, that's a CPP file which is devoted to search. I search first using LocationService and later using TextSearchIndex. For some reason, LocationService does not return bus stops. Do you know, if it supposed to return POIs by name as well? Like the cafe if coupled with the area?

Thank you very much for checking it out!

**Comment by Karry** [comment]
Yes, `LocationService` returned just objects with `Location` (and `Address`?) features (defined in map.ost). If something is POI and it has `Name` feature, Location and Address are assigned too...

I am surprised that it is not available in `TextSearchIndex` when bus stop has Name feature...

**Comment by rinigus** [comment]
It is available in `TextSearchIndex`, so you would get a hit if you search by the bus stop name only: Erottaja . However, if you search by bus stop name and the area ( Erottaja, Helsinki ) you wouldn't find anything. In the `TextSearchIndex`, we have just the names, right? Not with the area...

**Comment by Karry** [comment]
Yes. You are correct. Btw, I think that bus and tram stations should be POI definitely. I am sure that Tim will accept such MR.

**Comment by rinigus** [comment]
Thank you for checking it! I'll have to look then how to enable it. At least I have this issue in the system and should not slip :)

**Comment by rinigus** [comment]
Fixed by @Karry enhancements of the library
