### ISSUE TITLE
Searching brings unexpected results

### ISSUE THREAD

**Issue by a-dekker** [rinigus/osmscout-server#174]
Recently searches (Netherlands) give weird results. It doesn't find locations it previously did, or it returns for example a street name containing the name for the village I am searching for, but not the actual village.
Not sure if it related to the latest findings on TMO.

**Comment by rinigus** [comment]
Did it start with 0.14? I presume that you use 0.14.1, right? 
It could be related, but I don't know yet. 

Do you get maximal number of results or the number of results is small? I think limit for Poor Maps was 25... If it hits the limit then maybe we get it cut off of the results.

**Comment by rinigus** [comment]
I checked the size of geocoder-nlp dataset and that shrank to 90MB from 514MB earlier. So, that looks like the same bug we have for Norway (and very frustrating!).

**Comment by a-dekker** [comment]
I think it started with 0.14. If I do get result, it is for example 15x almost the same result. Let's say I searched for Amsterdam, It shows result like Amsterdamstreet in another town, but not Amsterdam itself. Some cities, like Almere are found.

**Comment by rinigus** [comment]
The fact that the database shrank 5x times suggests that we have the same issue as with Norway. I suspect that you were just lucky 15x and I have to look into it :)

**Comment by a-dekker** [comment]
Searching in the Netherlands works again in version 0.15.
Thanks!

**Comment by rinigus** [comment]
Thank you for feedback! Happy that it works
