### ISSUE TITLE
some map details missing (or advanced: possibility to adjust detail level)

### ISSUE THREAD

**Issue by schmittlauch** [rinigus/osmscout-server#207]
Some important (at least to me) details are not shown on osmscout-mapnik maps which are shown on the default openstreetmap.org card style (osm-carto). In this case it were certain POI names like [this student home](https://www.openstreetmap.org/way/74473622 ) which is quite relevant if you are looking for exactly this one.

relevant tags: `building: yes; name: name_to_be_displayed;`

bus stops also tend to be quite useful on a map.

This is a case where these information are shown on the OSM standard style, so it may be an easy choice to include this also into the osmscout-mapnik maps.
But the real problem is: Requirements for which POIS to display do not only differ from user to user, but also from time to time/ situation to situation. So it'd be good if they can be configured by the user.

But how to do that? Because of the client-server principle, the tiles are not rendered directly by the maps application but by the backend server. And this may be an UX challenge:

- either do all the settings in the backend application. Possibly easiest to implement, but requires change between to completely different applications (maybe with different UX concepts)
    - maybe also issues with cache invalidation/ updating the tiles in the maps client
- create an API for clients to set which information are rendered in which way
    - allows client integration
    - may need adjustments of clients
    - increases complexity of clients/ shifts responsibility to them

Especially because of these POI customization issues I tend to use Osmand still more often than osmscout-based native apps.

Any thoughts about
- the difference between the osm-carto style and the osmscout one
- possibilities to adjust displayed POIs
?

**Comment by rinigus** [comment]
There are several important aspects, indeed. I'll try to address them one-by-one.

First, house names are shown at rather large zoom levels. This was done to prevent too much data on lower zooms. In the case of the student house, its possible to find it using Search and it appears at high zooms rendered by Mapnik (see attached screenshot).

Second, the points regarding UX and cache invalidation are valid. One way to resolve them is to create a new style (server side) and a basemap description (client side) allowing you to switch between them through client. This already has been done for Poor Maps (released) and modRana, see default and car modes of the basemaps. Now making such styles is not trivial for those who are not used to that and it would be unfair to expect that casual user could just tinker the style to their liking.

Third, I am not sure whether you are familiar with the latest developments - I am working on getting Mapbox GL supported by SFOS and a new map widget based on it (see screenshot from development version of Poor Maps running one of the Mapbox GL styles on this widget). As a result, cache invalidation would go away - you render all on the client. The style manipulation is also much easier using GUIs developed for Mapbox GL styles. I think that this approach is the best for such custom style tuning and would relegate OSM Scout Server to data delivery and leave rendering to hardware-accelerated component.
 
![20171006083913](https://user-images.githubusercontent.com/15706605/31272646-5e865a7a-aa94-11e7-818d-4a871743ae5e.jpg)
![20171006083841](https://user-images.githubusercontent.com/15706605/31272647-5e889cea-aa94-11e7-9e1f-25762f65409e.jpg)



![20171006084014](https://user-images.githubusercontent.com/15706605/31272595-35613f98-aa94-11e7-9af2-d3a2f35b8113.jpg)

**Comment by schmittlauch** [comment]
The developments about MapboxGL sound really awesome!

> First, house names are shown at rather large zoom levels.

The choice of some level for when to show names is far too high IMHO, at least on the Jolla1. It's so high that it's above ModRanas maximum zoom level and even in PoorMaps you have to zoom so close to the building to see the name that it almost fills the screen completely. So you definitely have to know in which single building you're interested.

> One way to resolve them is to create a new style (server side) and a basemap description (client side) allowing you to switch between them through client.

I think there are two cases to differentiate:

- having a certain base style for a broader use: basemaps e.g. for cycling, car, walking (city), hiking
    - these should mostly be supplied by the app developer as defaults, maybe minor configurations
- narrow special interest informations on a map, looking for POIs (e.g. a restaurant) around. Then existing symbols/ POIs should be highlighted or new ones need to be rendered additionally
    - dynamically created by the user for current problems/ interests

**Comment by rinigus** [comment]
Re level: agreed, I should make the corresponding level lower. Originally, I wanted to make a systematic analysis for promoting POIs and names (https://github.com/rinigus/mapnik-styles-sqlite/issues/1), but now I better get Mapbox GL working and then we can optimize style(s) for that.

As for looking for restaurants and other objects, it should be also covered by search functionality (search nearby, for example). Although, having ability to flick POIs as shown/hidden should be easier via Mapbox GL - we have ability to make and remove layers on the map itself from clients. Assuming that the data is there on the corresponding vector tile at given zoom. Maybe we should revisit it after Mapbox GL is delivered. Please remind it if I'll forget about it.

**Comment by rinigus** [comment]
Closing as stale and as focus shifted to Mapbox GL tiles. Reopen if someone wishes to work on Mapnik backend
