### ISSUE TITLE
Do not drop POIs without name

### ISSUE THREAD

**Issue by palbr** [rinigus/osmscout-server#228]
As mentioned in https://talk.maemo.org/showthread.php?p=1539764&postcount=119, OSM Scout Server drops OSM POIs, which do not have a name.

This will delete many POIs (which are interesting for me) like parking lots, public toilets or playgrounds, since those typically do not have special names.

Example: Looking at the parkings lots in my home town, I see the following POI search results:

- OsmAnd: 3 parkings lots with names and 25 parking lots without a name
- PoorMap with OSM Scout Server: only the 3 parking lots with names

Could you please remove this filter criterion?

**Comment by rinigus** [comment]
I will look into it. It will probably blow up the database size for geocoding, but maybe its just a price to pay for such functionality.

**Comment by rinigus** [comment]
Closing here, resolved
