### ISSUE TITLE
Instructions to start server.

### ISSUE THREAD

**Issue by CaptainKhan** [rinigus/osmscout-server#229]
Cannot find the instructions to start the server in user guide, or in GitHub readme material. Please update.

**Comment by rinigus** [comment]
OK, sounds like documentation is not sufficient. At present, its stated in the end of "Mode of operation" that 

"On Sailfish OS, the normal mode of operation would require server running as one of the applications showing a cover and client opened as needed. Alternatively, the server can be activated automatically by systemd on request by the client. Such mode of operation allows client to access the server without exposing GUI of the server."

For now, let's see whether this will work:

* start OSM Scout Server
* minimize it to make it as just cover
* open Poor Maps
* select in Poor Maps, OSM Scout Server basemap.

If nothing will show up, please check OSM Scout Server logs and send them to me. Logs are shown in OSM Scout Server main screen. Either as screenshot or text file (later a bit more difficult, have to be enabled in settings, the last setting)

**Comment by CaptainKhan** [comment]
Ok that worked i used Poor Maps GL, which didnt work for some reason, Poor Maps worked though selecting OSM scout.

**Comment by CaptainKhan** [comment]
Thats slighly beside the topic here but for maps of Japan and with english as languahe selected (in OSm server) it still shows all text in Kanji format, in Poor Maps. Is there a trick to show them in english?

**Comment by rinigus** [comment]
Poor Maps GL would require vector maps. Which profile you selected in OSM Scout Server? Did it include vector maps as well?

For Mapnik maps (used by Poor Maps, not Poor Maps GL), you can enable English in OSM Scout Server Settings/Language (change Default to English). After that, clear cache in Poor Maps and you should get english names in Japanese maps.

The language selection that you may have used is for parsing the addresses when you search them, not for showing on maps.

I am working on making english names available for Mapbox GL backend as well

**Comment by rinigus** [comment]
Did you managed to get it work with Poor Maps GL?
