### ISSUE TITLE
Street names aren't showed in maps

### ISSUE THREAD

**Issue by carmenfdezb** [rinigus/osmscout-server#233]
I've downloaded last maps of Spain, but street names aren't showed. Does it happen only with Spain maps?

**Comment by rinigus** [comment]
Same was just reported via TMO for Germany. Try to stop Poor Maps GL, remove its cache

```
rm -rf ~/.cache/harbour-poor-maps-gl
```

and test again with Poor Maps GL.

(I assume the problem is with Mapbox GL, or is it with some other backend?)

**Comment by carmenfdezb** [comment]
I've removed cache and now it's working.
Thank you!!

**Comment by rinigus** [comment]
Thank you very much for reporting it! I'll add it to the notes at TMO and OpenRepos.
