### ISSUE TITLE
Add speed limits along route

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#24]
Add to the calculated route the indicators telling when the speed is limited. For that, a new postprocessor has to be written. Tim suggested to look at DistanceAndTimePostprocessor::Process() as an example.

**Comment by rinigus** [comment]
See email in libosmscout list. Vlad posted under thread "server" an implementation of the postprocessor

**Comment by Framstag** [comment]
I have now added the Description and Postprocessor classes in a slighty modified version to libosmscout.

**Comment by rinigus** [comment]
Thank you for letting me know. I'll take a look into it a bit later, the issue is mainly a reminder ...

**Comment by rinigus** [comment]
Dropping old libosmscout issues, no time to address them. Can be reopened later if someone wants to maintain this backend.
