### ISSUE TITLE
OSM Scout Server fails to start its Valhalla routing engine

### ISSUE THREAD

**Issue by Olf0** [rinigus/osmscout-server#242]
OSM Scout Server's log always shows the block:![screenshot_20180402_002](https://user-images.githubusercontent.com/16547876/38178935-0843fc48-361d-11e8-87bf-f077b3ae8c04.png)

Tested with OSM Scout Server 1.4.3-10.29.1.jolla and OSM Scout Server Module: Route 2.4.8-10.16.1.jolla (plus OSM Scout Server Module: Fonts 0.10.0-1) on a Jolla 1 phone under SailfishOS 2.1.4.14.

Any hints how to investigate this further?
Or does above contain sufficient information to decide if this is a bug or just a configuration error?

**Comment by rinigus** [comment]
Good morning! For some reason, old Valhalla process is still running in the background. So, please close WhoGo maps and all other map clients, close the server. Then, in terminal, check if any remaining processes are running :

```
ps -u nemo | grep osm
```

kill them if there is any (I expect at least one). start the server and see if it helped.

**Comment by rinigus** [comment]
As an alternative, you could also just reboot the phone. This should have the same effect

**Comment by Olf0** [comment]
@rinigus, thanks.  I rebooted meanwhile, anyway (hence `ps -u nemo | grep osm` outputs nothing).
Thus closing this issue, but will watch, if this occurs again (and hopefully in a reproducible manner).

**Comment by Olf0** [comment]
BTW, the only thing Valhalla now complains about is:
    INFO: Valhalla: [WARN] /data/valhalla/evelation/ currently has no elevation tiles
Just a wish: It would be really useful, if an elevation profile of a route could be taken into account (someday in the future), especially for bicycle routing (as Brouter does for OSMand under Android).

**Comment by rinigus** [comment]
I hope it will not occur again :)

As for elevation support, that should be possible. I have opened an issue regarding it: https://github.com/rinigus/osmscout-server/issues/244
