### ISSUE TITLE
harbour-osmscout-server crashes if libosmscout-related profiles are selected.

### ISSUE THREAD

**Issue by persmule** [rinigus/osmscout-server#266]
I have been using harbour-osmscout-server with libosmscout-related profiles for a long time, but recently, such config will result crashe (on my Sailfish X running on an Xperia X). I managed to launch harbour-osmscout-server under console, and get the following error report:

> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::json_parser::json_parser_error> >'
  what():  <unspecified file>(1): expected object or array
aborted

with gdb I obtained the following backtrace:
> (gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xf5dfb2dc in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xf5dfe212 in __GI_abort () at abort.c:89
#3  0xf6e2a70c in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#4  0xf6e2912c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:38
#5  0xf6e29148 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0xf6e29384 in __cxxabiv1::__cxa_throw (obj=0xabc74278, tinfo=<optimized out>, dest=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#7  0xaad53b76 in ?? ()
#8  0xaad53b76 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Selecting profiles without libosmscout will not crash the harbour-osmscout-server, but I do not want to use those far larger data sets.

Please fix this issue.

**Comment by rinigus** [comment]
which profile do you use specifically?

**Comment by rinigus** [comment]
Thanks, I can reproduce the issue. Will look into it

**Comment by rinigus** [comment]
It was induced by init of Valhalla lib, even its not enabled in the profile. The bug is fixed now (or at least should be). If you wish, you could get the current build at http://repo.merproject.org/obs/home:/rinigus:/maps/sailfish_latest_armv7hl/armv7hl/ , before I will make the release.

**Comment by persmule** [comment]
The change fixed the issue I faced. Thanks.
