### ISSUE TITLE
include an option not to use tolls

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/osmscout-server#268]
well the title pretty much explain everything, it would be nice to have a way to calculate routes with tolls or not :)

**Comment by rinigus** [comment]
Valhalla supports avoiding tolls already. Its a matter of the client (WhoGo Maps, modRana) to trigger this option. So, please open the issue in the client that you prefer and, when done, let's close it over here.

**Comment by legacychimera247** [comment]
ah that's nice, will do it right now
