### ISSUE TITLE
use mapbox satellite streets offline

### ISSUE THREAD

**Issue by legacychimera247** [rinigus/osmscout-server#274]
i know it may be a large amount of data, but it would be very nice to have the ability to use mapbox satellite streets maps offline, for navigation in whogo maps. as of now it's already present but only online...would be nice to have it offline too...

**Comment by rinigus** [comment]
I don't have access to mapbox satelliti images. So, the first problem will be to get images. Second, I think its just too much data to push somewhere and trying to keep updated. So, we are talking about time to investigate it, and server / network requirements. I am not planning to work on it, to be straightforward about it. I presume, after some inactivity, unless someone shows up wishing to implement it and provide server/network bandwidth, I will close the issue as non-fix.

**Comment by rinigus** [comment]
closing until someone would like to work on it
