### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by adnion** [rinigus/osmscout-server#276]
Do you use the travis build.sh and install.sh scripts for installation?
I found no installation instructions.
Help is very much appreciated.

**Comment by rinigus** [comment]
Hi,

The main complexity in building is to figure out what you want to be supported and installing required backend libraries. So, it depends on what you would like to get:

* do you want raster tiles (Mapnik or libosmscout) or vector tiles (Mapbox GL)? Mapbox GL doesn't need any libs, its served from SQLite databases. Mapnik and libosmscout require corresponding libs.

* do you want routing support by Valhalla? Then you would have to install valhalla¸ see install script in https://github.com/rinigus/pkg-valhalla-lite/blob/master/rpm/valhalla-lite-devel.spec

For geocoding, you will need geocoder-nlp requirement - libpostal. Please install it on the basis of https://github.com/rinigus/pkg-libpostal/tree/devel . There is a nasty bug upstream of libpostal which hasn't been fixed yet => use my tree for now.

After requirements are all there, I suggest to build Qt Controls version. For that, copy/link pro/osmscout-server_qtcontrols.pro to the root and open the project in Qt Creator. Alternative is to use qmake and disable backends that you don't want (see build.sh that you referred to for example).

Recommended configuration is with Mapbox GL, GeocoderNLP (so libpostal is needed), and Valhalla. 

Please don't hesitate to ask if something is not clear

**Comment by adnion** [comment]
In QtCreator i get:
osmscout-server-1.10.2/src/dbmaster.h:25: error: osmscout/Database.h: No such file or directory
 #include <osmscout/Database.h>

And with 'qmake osmscout-server_qtcontrols.pro' i get:
Empty filename passed to function
QDir::mkpath: Empty or null file name
WARNING: Cannot create directory ''

**Comment by rinigus** [comment]
You forgot to remove non-used backends:

```
qmake CONFIG+="disable_mapnik disable_osmscout disable_systemd" osmscout-server_qtcontrols.pro
```

Let me know if it helps

**Comment by adnion** [comment]
Thank you for the suggestion. I get the same error. 
However in QtCreator I could compile some files but even after cleaning the build and disabling osmscout it terminates with "osmscout/Database.h: No such file or directory" (searchresults.cpp)

**Comment by rinigus** [comment]
OK, then its a bug. I have pushed a fix right now (26a3c3cc023cf95fbbaa5f33cc2f7b835cc7e653), please refresh your copy and try again

**Comment by adnion** [comment]
I got many other errors in QtCreator. Undefined references to sqlite3pp and valhalla but both are installed.
The one thing that is missing in the docs are build instructions for the average user. I can imagine I made a stupid configuration mistake as I commented out some += dependencies in the .pro file that I don't want.

osmscout-server-master/src/geocoder-nlp/src/geocoder.cpp:628: error: undefined reference to `sqlite3pp::query::query(sqlite3pp::database&, char const*)'

/usr/include/sqlite3pp.h:243: error: undefined reference to `sqlite3pp::statement::~statement()'

osmscout-server-master/src/valhallamaster.cpp:192: error: undefined reference to `valhalla::tyr::actor_t::actor_t(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool)'

**Comment by rinigus** [comment]
Re sqlite3pp: this is actually pulled as a submodule by geocoder-nlp. So, when cloning the source, you have to pull recursively submodules. I am using header-only version, hence no need to add library for compiling.

Re valhalla linking: strange, that should have been resolved with PKGCONFIG. Can you post full make log? And the version of Valhalla that you have.

Re average user: I believe you are the first one to do so. All users so far have used it on Sailfish where its packaged. I'll open an issue regarding it and will fix documentation in time. Thanks for working on installing it!

**Comment by rinigus** [comment]
Build instructions are given in a separate document, INSTALL.md at the repository. Its also possible to install the server as a flatpak, see INSTALL.md

Closing the issue
