### ISSUE TITLE
sometimes roundabout exit is wrong

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#28]
for example, routing tln->tartu

**Comment by Framstag** [comment]
The calculation of exists is tricky. I have to look at the code, but exists are only ways, that are in principle routable. So they may be ways connected to the roundabout which are not counted as exits. For a proper analysis I need a concrete case. That means:
* osm.pbf file to import
* Parameters for the Routing demo to calculate a route from some start to end point.
* Hint, which roundabout exit calculation is wrong and why

**Comment by rinigus** [comment]
I agree, its tricky. I'll take a look and will try to find an example where its failing. I'll submit it then better to libosmscout proper :)

**Comment by rinigus** [comment]
Dropping old libosmscout issues, no time to address them. Can be reopened later if someone wants to maintain this backend.
