### ISSUE TITLE
allow searching without libpostal parsing

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#280]
requires https://github.com/rinigus/geocoder-nlp/issues/55

On slower hardware (J1), libpostal parsing takes rather long time. Allow users to specify "use primitive parser" (done) and, if enabled, "primitive parser only".

**Comment by missinglink** [comment]
Which parser you planning on using for the 'primative parser'?

**Comment by rinigus** [comment]
I have this parser that just splits a string by commas and builds a hierarchy from inner to outer levels using it. => primitive :)

**Comment by missinglink** [comment]
Might it be possible to extract and use the parser from the TIGER geocoder?

I didn't really look into it yet, and it would likely only support US-style addresses...

- https://postgis.net/docs/Pagc_Normalize_Address.html
- https://postgis.net/docs/Normalize_Address.html

**Comment by rinigus** [comment]
Well, its mainly for users on very old hardware (5 years old) and I see this as a transition that will be not needed soon. In this sense, it seems to be adequate to enable the use of the primitive parser that I have  already and not to invest too much time into it. But thank you for suggestion!
