### ISSUE TITLE
Check packaging for SFOS - boost changes

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#289]
On SFOS3, different version of boost will be provided. Ensure that we don't require anything from outside of the bundled libs

**Comment by Karry** [comment]
Hi Rinigus. Where you saw such low-level information about SFOS3? Somewhere in git.merproject.org ?

**Comment by rinigus** [comment]
Hi @Karry 

no, I had two users approaching me (one of them at https://talk.maemo.org/showpost.php?p=1549361&postcount=566) and warning that the version of boost will change. I had one of the boost libs linked to the system version and not bundled into the package. This got fixed by ddf2d859909aea5de528471c367ed00aae94917d . Now just got conformation via private message that its all fine.
