### ISSUE TITLE
Minor translation / source string issue in src/mapboxglmaster.cpp

### ISSUE THREAD

**Issue by Olf0** [rinigus/osmscout-server#298]
@rinigus,
when translating
>
    <message>
        <location filename="../src/mapboxglmaster.cpp" line="161"/>
        <source>Failed to run query in Mapbox GL database: %1</source>
    </message>
    <message>
        <location filename="../src/mapboxglmaster.cpp" line="212"/>
        <source>Failed to run query in Mapbox GL fonts database: %1</source>
    </message>

I wondered, if you want express something explicitly by using "... to run query in ..." instead of just "... to query ...".
On first sight these two strings appear to simply state that asking the DBMS for a data-set failed.  If so, a simple "Failed to query Mapbox GL ..." (twice) would be appropriate, IMO.

**Comment by rinigus** [comment]
I had different strings to make sure that I can find where the error is coming from (in the code). This argument goes out of the window in the case of translations, unless translations are different as well. Although, so far, nobody has come with those and asking for help :)

As for "to run query" vs "to query" -> just probably late evening coding and not really necessary word. However, let it stay to avoid pinging all translators for removing it.

**Comment by Olf0** [comment]
Thanks for the prompt reply.
To put this question into context: After fixing the "Mabox" typo (and missing the "Vailed", which you corrected meanwhile), I went to Transifex and found four new source strings, of which the meaning of these two was not absolutely clear to me.  Thanks for clarifying that they weren't phrased to express anything special.
But this reminded me that I had to read a few explanations multiple times, to be sure about their exact meaning.  Looking for them, I found four, which exhibited a little lax use of grammar (singular vs. plural, use of articles "a", "the" or nothing) making them a bit hard to comprehend.  Please note that someone nicknamed me "language nazi" and most source strings are very well phrased and "on the spot" WRT their meaning, hence no criticism implied with these statements.

* If it is O.K. for you, I will try to create a PR with these five source strings slightly adapted the next weekend.
* There is no need to notify the translators, as there is no change in the meaning of these strings.
* This time, I will perform all changes in all files in a single commit.
  Alternatively, I can put each string change (across multiple files) in a single commit (just tell me, if you prefer that).  This way you may merge the commits you like and reject the other ones.
* I might also alter "Mapbox GL World ..." (e.g. "... coastlines") to "Mapbox GL world ..." in a few strings (as they are not about the "Mapbox GL World", but the "world coastlines / map"). Sure, "World" can be written with a capital "W", when it explicitly addresses Earth (so it is rather used as a name than an ordinary noun), but that becoming uncommon and is slightly confusing when another name is directly preceding it; I guess people became familiar with the idea that many other worlds exist.

**Comment by rinigus** [comment]
Please do so! Its of great help when such polishing is done, please feel free to choose number of commits as it is easier for you. And please alter Mapbox GL World, as needed :)

**Comment by rinigus** [comment]
Closing as stalled :)
