### ISSUE TITLE
Improve description of settings logic

### ISSUE THREAD

**Issue by Olf0** [rinigus/osmscout-server#303]
As a reminder, see [PureMaps issue \#241](https://github.com/rinigus/pure-maps/issues/241#issuecomment-487379965) for details.

P.S.: @rinigus, you may assign this one to me, and issue #298 also.

**Comment by rinigus** [comment]
Excellent, any help is welcome! Alternative is to make it properly and show Valhalla/libosmscout as a combobox. Then it will be easier to describe it as well. Should I prep comboboxes and let you write description?

**Comment by Olf0** [comment]
If changing the three radio buttons for the bitmap map provider, geocoder and routing engine to combo-boxes (each offering two choices: X and libosmscout) is easy to implement: yes, please.
This change would make it obvious what to choose from and what is currently set.
Hence this would also alleviate the need for adapting the description a lot: The current description fits quite well, if three combo-boxes are introduced, though I still have some ideas for making it a bit more concise (hence please leave this issue open when introducing combo-boxes).

**Comment by rinigus** [comment]
Its quite simple, so let's do that. I'll ping you when its ready

**Comment by rinigus** [comment]
The comboboxes are used for showing the selection. Here is an example screenshot

![osmscout_sc](https://user-images.githubusercontent.com/15706605/57098833-acafdc00-6d23-11e9-8695-b273bfab6c72.png)

**Comment by Olf0** [comment]
This screenshot is looking really fine.
(And now I had a peek at how nice OSM Scout Server looks on a PC.)

Minor remark:
Thinking of mobile devices in portrait orientation, it may make sense to put the combo-boxes *under* their corresponding settings (i.e., not to the right of them, side by side).
Or rather eliminate them (the terms preceding each combo-box) completely, they are just a repetition of the section title, anyway (i.e., with only a combo-box remaining  in each of these three lines).

**Comment by Olf0** [comment]
Thinking about the screenshot, actually all three "**This server allows you to select between [...]: [...] and** ***libosmscout***" have become superfluous and can be deleted, as this is "stating the obvious" now and these are strings, which are easily forgotten to adapt when adding more backends.

**Comment by Olf0** [comment]
As with my suggested changes there would be no text left in the **Rendering** section:

The rendering backend is responsible for drawing the maps.

**Comment by rinigus** [comment]
The changes are in (removal of selection text and adding rendering bg task description). I think its looking fine now. Will keep it alive for response and, in my mind, we can close it.

**Comment by Olf0** [comment]
Ack.

**Comment by Olf0** [comment]
BTW, for the final check, I looked at  the code (which I should have done earlier, as it answers a couple of my sub-questions), I noticed the new line in the license header: Congrats, it looks that all your efforts were ultimately worth (now also literally) it for you.

**Comment by rinigus** [comment]
Thanks!
