### ISSUE TITLE
OSMScout-Server native support for Garmin .img map files

### ISSUE THREAD

**Issue by ferlanero** [rinigus/osmscout-server#309]
As Garmin .img map format becoming more and more popular

Is there any chance to get native support for Garmin .img files? On Android, Locus or Oruxmaps can do it. 

Adding support for this so popular format would turn OSMScout -Server in an authentic Swiss knife.

More info:
[https://en.wikipedia.org/wiki/Garmin_.img](https://en.wikipedia.org/wiki/Garmin_.img)
[https://alternativaslibres.org/en/index.php](https://alternativaslibres.org/en/index.php)

**Comment by rinigus** [comment]
Hi @ferlanero: adding new format would require writing new backends (search, geocoding, routing, map display). Its a major work and I don't expect to do it in any foreseeable future. Closing the issue.
