### ISSUE TITLE
Segfault when routing

### ISSUE THREAD

**Issue by otsaloma** [rinigus/osmscout-server#31]
Trying the following

```
http://localhost:8553/v1/route?type=car&p[0][search]=Helsinki&p[1][lng]=24.900393&p[1][lat]=60.193096
```

The server seems to segfault

```
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL 
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:103 - Could not find any zN.M subdirs! 
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:129 - Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/" does not exist 
Automatically closing FileScanner for file '/home/nemo/Documents/Maps/location.idx'!
60.1674 24.9426
60.1931 24.9004
From:                Way 729444[12 *> 3795564248010254337]
To:                  Way 1633124[3795564573483336193 >* 16 *> 3795564590577356801]
Time:                0.093
Route nodes loaded:  4847
Route nodes ignored: 10659
Max. OpenList size:  176
Max. CloseMap size:  4774
Segmentation fault
```

This crash is also probably the reason I earlier saw bad status line and connection refused errors when looking the output from Poor Maps.

Using Mapzen Metro Extract for the Helsinki region.

**Comment by rinigus** [comment]
Thank you very much! I can reproduce it on the desktop as well - should be easy to debug!

**Comment by rinigus** [comment]
This bug has been fixed in the upstream library. I will test the fix a bit further and then publish a new release with the bugfix

**Comment by rinigus** [comment]
Fixed at https://github.com/Framstag/libosmscout/issues/148 . It does require re-importing maps again to avoid the incorrect paths. Closing this bug.
