### ISSUE TITLE
[RFC] Support of SailfishOS releases 3.0.2 and below?

### ISSUE THREAD

**Issue by Olf0** [rinigus/osmscout-server#318]
As this topic is coming up regularly, first addressed by a [separate OBS repository](http://repo.merproject.org/obs/home:/rinigus:/maps/sailfish_3.0.2.8_armv7hl/), now running into a [new issue](https://openrepos.net/comment/30928#comment-30928), creating this pseudo-issue as a single point to collect comments, opinions etc.

#### Reasons to stay on older SailfishOS releases
* Intex Aquafish phones do not receive any SailfishOS upgrade beyond v2.2.1 at the GUI (presumably because Intex stopped paying Jolla for support).
   Although they can be manually upgraded at the command line to SailfishOS 3.0.0 and subsequently to 3.0.1, doing so for SailfishOS 3.0.2 or higher breaks the SailfishOS installation.
* The situation for the Jala phones Accione and Accione P seems to be similar (likely for the same reason).
* Many of the [community ports](https://wiki.merproject.org/wiki/Adaptations/libhybris) are stuck at older SailfishOS releases.
* With each SailfishOS release since (and including) 3.0.0 little things seem to break on the older Jolla devices, especially the Jolla 1, e.g. the "WLAN hotspot" functionality.
  I do not expect any if these being fixed, as resources at Jolla are scarce, hence these flaws accumulate with each new release.
* Obviously and understandably Jolla seem to perform only basic testing with new SailfishOS releases on all their supported devices older than the Xperia X (Jolla 1, Jolla Tablet, Jolla C; devices once sold and supported by Intex and Jala / Accione are EOL, anyway) since (and including) SailfishOS 3.0.0.

In terms of functionality, SailfishOS 2.2.1 (the last v2.x) seems to be the "golden release" for all these older devices (i.e., all before the Xperia X).

#### Reasons not to support SailfishOS releases before 3.0.3 any longer
Structurally the issues and efforts to continue supporting older SailfishOS releases can only become larger over time.
Even though I own a Jolla 1, which will stay on SailfishOS 2.2.1, I think that working on forward looking things (such as general fixes and improvements, also benefitting recent devices) may be a better use of the limited resources than pursuing this.

#### A suggestion for resolving this
Currently no working version of OSM Scout Server built for SailfishOS 3.0.2 and older seems to be available (as v1.15.0 at the Mer-OBS was reported to crash on startup).
This may be resolved by rebuilding v1.14.5 in the Mer-OBS as it was (end of May 2019) and uploading the RPMs relevant for installing it to a new, separate "OSM Scout Server for SailfishOS 3.0.2 and older" repository at OpenRepos.
Then leave it as it is, unless somebody volunteers to make the recent versions of OSM Scout Server's components (e.g. Valhalla) compile for and working under SailfishOS 3.0.2 and older.

#### Open questions
Did some file format of the ones offered for download change from v1.14 to v1.15?
If so the whole suggestion is fruitless.  Then it may really make sense to assess the effort to make it compile for SFOS <= 3.0.2 and decide for "go / no-go".

**Comment by rinigus** [comment]
Unfortunately, file format has changed (Valhalla got to 3.x). I will look into whether I can enable these builds in 10-15 minutes of my time tonight. Its possible that this is easy to fix. Its also possible that we have some other bug that gets exposed in earlier SFOS versions. In this respect it would be advantageous to get old SFOS versions supported.

**Comment by rinigus** [comment]
I was wrong, 3.0.2 repo already has opt-gcc compiled with the older SFOS release. So, it should be "clean" in the sense that its not mixing latest SFOS release with the earlier one. Which indicates that its a possible bug in the server or Valhalla and that this bug is triggered only in the older SFOS versions. No idea how to debug it though... 

Maybe running with gdb and using backtrace will help to figure out where it happens?

**Comment by Olf0** [comment]
Mhhh, sounds basically feasible, although the last time I used gdb is more than 20 years ago.  But a my "production Jolla 1" died, I first have to migrate to my Xperia X, flash my XA2 with SailfishOS 3.2, before my "testing Jolla 1" can be used for testing again.
@markkyboy / @Edz ?

**Comment by Markkyboy** [comment]
What does this have to do with me?

**Comment by Olf0** [comment]
@Markkyboy, only if you are interested.
I thought you may, because this is about having OSM Scout Server 1.15+ functional or not (in the light the downloadable data formats changed compared to v1.14) on Jolla 1 phones.  And you seem to be one of the very few tech-savvy Jolla 1 users remaining.

**Comment by Olf0** [comment]
Sorry, I just realised my confusion due the doing too many things concurrently (when I had to stop: under the shower): Somehow I implicitly assumed (without being aware of that), that other Jolla 1 users have also chosen to keep SailfishOS 2.2.x.

**Comment by Markkyboy** [comment]
Hi Olf0 - yes, I have 2 x Jolla1 devices, but both are on 3.1.0.11 and I rarely use maps on either devices, when I do, I have found Sygic (yes, I know, bloody Android apps!) to be the most reliable and functional.

I have no real desire to fall back to an earlier version of SFOS, despite much disappointment with the lack of speed and progress of SFOS, I still look forward to subsequent OS updates.

**Comment by rinigus** [comment]
With SFOS 3.3 and its updated compiler, I can see only issues with trying to support older builds. If someone would really like to have it, please make new builds at OBS. With time, I can see only increasing amount of patches that maybe needed to make such builds possible. Closing here and sorry for such outcome.
