### ISSUE TITLE
Pure Maps doesn't see the OSM Scout on Ubuntu Touch

### ISSUE THREAD

**Issue by pmiko** [rinigus/osmscout-server#323]
Hi,
I installed both OSM Scout and Pure maps as recommended (including disabling background suppression), however there appears no "offline" option in the Pure maps menu section, I also cannot select OSM Scsectiona map source.

In the OSM Scout Profile Selection the scroll-down menu doesn't open, so I can't choose the profile (see the picture). All other stuff seem to be working well..

Do you have any ideas?

Thanks a lot

Pavol

![screenshot20200229_115840514](https://user-images.githubusercontent.com/49643619/75606225-e2ac2100-5aea-11ea-83e8-88eb1a01f316.png)

**Comment by rinigus** [comment]
Re not opening profile - I have no idea why it is so. @jonnius - do you know whether it ever worked on UT?

Re absence of offline profile: it could be due to detection mechanism used in Pure Maps. @jonnius - do you have executable osmscout-server in path for Pure Maps? I presume you had it before...

**Comment by jonnius** [comment]
Which is your device and whih UT channel? For me both things work and you are the first one to report them.

**Comment by pmiko** [comment]
I have Fairphone 2 and Ubuntu 16.04 (OTA-11), the Channel section says 'stable'.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 29. Feb. 2020, 15:11, jonnius schrieb:

**Comment by pmiko** [comment]
Sorry guys, I reinstalled the OS yesterday for different reasons and now I see, the 'offline' button has appeared. So the issue is solved.Thanks a lot.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 29. Feb. 2020, 15:11, jonnius schrieb:

**Comment by rinigus** [comment]
Excellent! Closing
