### ISSUE TITLE
Merge OpenAddress data into OSM data

### ISSUE THREAD

**Issue by joshbowyer** [rinigus/osmscout-server#328]
OpenAddress data is far more complete than OSM data, and merging the two datasets makes OSM very usable. Data is available from OpenAddress.io in csv format, and if needed, I already have a script that converts it to .osm and merges with OSM data (.osm format) for US states.

**Comment by rinigus** [comment]
When looking into openaddresses, we are talking about a map 

streetname, housenr, coordinates

At least in Finnish addresses, town and other hierarchy info is not there. In the server's geocoder, I am using hierarchy info. Namely, each coordinate is associated with city, region, country and so on. So, on import, we will have to determine those as well. 

I want to make new importer for the data as it currently depends on an outdated version of a lib. So, it will be practical to work on it after that.

Ideally, what is needed is some kind of tool that will take OSM/OpenAddresses data and organize it in hierarchical manner allowing me to queue the hierarchy of objects and write them in my own format for https://github.com/rinigus/geocoder-nlp .

**Comment by joshbowyer** [comment]
Any update on this? As far as the prerequisite work to be done before this can be tackled? Just curious, not trying to rush

**Comment by rinigus** [comment]
No progress so far, have been working on unrelated project. Hopefully I can get into some reasonable stage in that other project soon and then share time with the work on maps. With the maps, the rewrite of navigation for Pure Maps would take precedence to this as I have been researching already for that rewrite. So, by the look of it, not that soon I can start working on this.

**Comment by joshbowyer** [comment]
Just a heads up, I went to check the OpenAddresses stuff again and they recently changed the main format of the data to JSON instead of CSV, so that might make things easier.

**Comment by rinigus** [comment]
As the import is done via Nominatim now, I am closing it here. As soon as nominatim will add that source, I can add it to OSM Scout Server as well.
