### ISSUE TITLE
Add headers to the response

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#335]
Looks like we are missing some HTTP headers which make it harder to use the server. Check meaning of   Access-Control-Allow-Origin, Access-Control-Allow-Headers and add them as needed.

Reference: https://github.com/costales/unav/issues/8#issuecomment-673039766

**Comment by costales** [comment]
Hi,

Well... probably was my fault, that I didn't allow the QML to access in js the server...

I would not touch the code if someone hasn't issues :)

A hug and thanks for your support.

**Comment by rinigus** [comment]
Even better, closing it then. Maybe the fastest resolved issue for the server :)
