### ISSUE TITLE
Osmscout-server not starting automatically (Mobian)

### ISSUE THREAD

**Issue by boroli** [rinigus/osmscout-server#337]
I installed osmscout-server and PureMaps on Mobian (Debian+Phosh) via flatpak. At initial start of Osmscout-server I selected to let PureMaps let it start in the background automatically. This setup worked fine on sailfishOS and UbuntuTouch.

Is there a possibility to check, what prevents it from automatically startup?

**Comment by rinigus** [comment]
It does not work on UbuntuTouch, as far as I know. It is using systemd socket activation and is not supported when running through Flatpak. To make it work, someone has to package OSM Scout Server as deb. I know that there was some interest and maybe there are bits packaged already, but I don't think the efforts are made public yet.

Ask around on Mobian and/or librem-5 channels

**Comment by rinigus** [comment]
Closing here as it is Flatpak limitation
