### ISSUE TITLE
Valhalla: version of dataset for  Australia and Oceania  New Zealand is not supported 

### ISSUE THREAD

**Issue by sbridger** [rinigus/osmscout-server#340]
The map for Australia and Oceania  New Zealand   downloads but says

Valhalla: version of dataset for  Australia and Oceania  New Zealand is not supported 

Missing dataset: missing Valhalla tiles

This appears to make the whole map unavailable.

**Comment by rinigus** [comment]
Strange. Few questions:

- Can you download any other regions? Try something in EU

- Do you have the latest version of OSM Scout Server?

**Comment by sbridger** [comment]
1.13.1-1.107.1
Any map I select (eg germany, hamburg) it says 
```
Valhalla 61MB
22/07/2020
incompatible version
```
OK so current seems to be 1.17. strange -
storeman shows no updates. I have removed it, and try to install 1.17 with storeman:

"nothing provides libicuuc.so.63"

sfos v3.4.0.24

**Comment by rinigus** [comment]
Then you have to update OSM Scout Server to get the maps as the format changed later. There is no release of the server supporting SFOS 3.4.0.24. you would have to wait until OBS target will become available at https://build.merproject.org/project/subprojects/sailfishos

Closing as it is expected state.
