### ISSUE TITLE
[sailfishos] OpenRepos package broken on 3.4

### ISSUE THREAD

**Issue by ntninja** [rinigus/osmscout-server#341]
After upgrading to SailfishOS 3.4.24 OSM Scout Server was uninstalled and cannot be installed anymore. The error message suggests that it depends on `libicuuc.so.63` which probably just had a soname bump. As such, please recompile the package for 3.4, to make it installable again.

**Comment by rinigus** [comment]
Sure. As explained in OpenRepos comments, the new package version will be compiled as soon as OBS will get the new target. 

Thanks for opening an issue to keep it tracked.

**Comment by ntninja** [comment]
Oh, didn't see that! Sorry!

**Comment by rinigus** [comment]
No problem, it is OK to have it as an issue
