### ISSUE TITLE
Bump Valhalla to 3.1

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#349]
Valhalla has released a new version, switch to it.

**Comment by Thra11** [comment]
FYI, trying to run current master with valhalla 3.1.0:
```
<bunch of qml warnings>
file:///nix/store/y5jd5nwk1lb61shrpkv8fzcl5z5xqiiv-kirigami2-5.78.0/lib/qt-5.15.2/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml:139:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::ptree_bad_path>'
  what():  No such node (service_limits.isochrone.max_time_contour)
/tmp/nix-shell-19017-0/rc: line 1: 19341 Aborted                 (core dumped) osmscout-server
```
isochrone.max_time_contour is in valhalla.json-3.1, added in 584de8bd47700053960fa139a2d7f8d3d184c876

**Comment by rinigus** [comment]
You have to use https://github.com/rinigus/osmscout-server/blob/master/data/valhalla.json-3.1 as valhalla.json to get it fixed already now. Just after install, replace valhalla.json in /usr/share/... with that version. Then it should work

**Comment by Thra11** [comment]
Thought it must be something I was doing wrong!

**Comment by rinigus** [comment]
Follow https://github.com/valhalla/valhalla/issues/2855 and similar before bumping Valhalla version

**Comment by rinigus** [comment]
Switched to Valhalla 3.1 by default
