### ISSUE TITLE
[Kirigami UI] Some text is very hard to read when using a dark theme

### ISSUE THREAD

**Issue by PureTryOut** [rinigus/osmscout-server#354]
I use Breeze Dark as my system theme, and some pages are very hard to read for me (I'm colorblind, maybe that matters in this case).

![Screenshot_20210302_131450](https://user-images.githubusercontent.com/1565836/109648234-adea0400-7b5a-11eb-824b-e10678a6a055.png)

Not all pages are like this though, it seems just the "Country subscription" pages as everything else uses clearly readable white text.

**Comment by PureTryOut** [comment]
Actually, some more locations

![Screenshot_20210302_132845](https://user-images.githubusercontent.com/1565836/109648722-408aa300-7b5b-11eb-93d3-b94e00b906b9.png)

**Comment by jonnius** [comment]
I can confirm that the contrast on that screen shots makes it impossible to read the text also for a person that is not colour blind.

**Comment by rinigus** [comment]
I was adjusting colors of the text for clickable elements and did not take into account dark variant. Replaced with the plain link colors, should be OK now.
