### ISSUE TITLE
[Kirigami UI] The "Language" label in settings doesn't fit in the window on wide screens

### ISSUE THREAD

**Issue by PureTryOut** [rinigus/osmscout-server#355]
Note the "Language" label in the screenshots below.

![Screenshot_20210302_132659](https://user-images.githubusercontent.com/1565836/109648492-fa354400-7b5a-11eb-8057-23afeb9b9ae2.png)

![Screenshot_20210302_132742](https://user-images.githubusercontent.com/1565836/109648588-120cc800-7b5b-11eb-9d8a-f679fd15603c.png)

**Comment by rinigus** [comment]
Had the same issue in Pure Maps, disabling wide mode for now. Opened now an issue in KDE Bugzilla and linked to the issue in the server to enable wide mode back. Let's see if it is indeed a problem with Kirigami and, if it is, when it will be fixed.
