### ISSUE TITLE
Can't start Pure Maps withought net

### ISSUE THREAD

**Issue by CesarHerreraG** [rinigus/osmscout-server#373]

**Comment by rinigus** [comment]
You have to be more specific. Is this Pure Maps issue or OSM Scout Server? Platform? Version(s)?

**Comment by CesarHerreraG** [comment]
I think thisbis a problem with the server. I updated an it was imposible start Pure Maps offline.

**Comment by CesarHerreraG** [comment]
I received this. But if I go back I can see the map. No problem then. Sorry.

**Comment by CesarHerreraG** [comment]
You reffer to "Preferences"?

**Comment by CesarHerreraG** [comment]
El Tue, 30 Mar 2021 12:13:21 -0700, Jonatan Hatakeyama Zeidler escribió:
> Does routing work for you?
>Don't understand.

-- 
Sent using Dekko from my Ubuntu device

**Comment by CesarHerreraG** [comment]
El Tue, 30 Mar 2021 12:32:47 -0700, Jonatan Hatakeyama Zeidler escribió:
> And if you go to the settings page again, is the error message gone?
>No

-- 
Sent using Dekko from my Ubuntu device

**Comment by CesarHerreraG** [comment]
El Tue, 30 Mar 2021 12:32:47 -0700, Jonatan Hatakeyama Zeidler escribió:
> And if you go to the settings page again, is the error message gone?
>Everything ok.

-- 
Sent using Dekko from my Ubuntu device

**Comment by jonnius** [comment]
Good to hear everything works for you now. :)

**Comment by rinigus** [comment]
@jonnius thanks ! closing.
