### ISSUE TITLE
Can't open settings (Ubuntu Touch)

### ISSUE THREAD

**Issue by spctrlth** [rinigus/osmscout-server#374]
Hey,

when I click the hamburger menu, the menu won't open. This means I also can't install offline maps any more :(

I gotta be honest and say that I was playing around before I noticed this (including manually removing Maps.OSM in the home folder), but afterwards I did a complete wipe and install of my UT device, installed OSM Scout Server, and the problem persists... So not sure if it's me who did something wrong, but maybe?

Logs can be found at http://paste.ubuntu.com/p/32MK4dkcnW/

Version is latest stable release: Ubuntu 16.04 (OTA-16)

**Comment by spctrlth** [comment]
Huh, I also notice that I get the "Welcome" screen each time I start up. The one where you have to set profile, then language for parsing addresses (the languages I chose are still selected)...

**Comment by rinigus** [comment]
Which version of OSM Scout Server is it? Looking at the logs, I can see 2.0.0 - did you get the latest version released last night?

**Comment by rinigus** [comment]
We just troubleshooted it with @jonnius and the new release with the bugfix is on the way.

Closing here. If something is still wrong, open a new issue or reopen this one.

**Comment by spctrlth** [comment]
Awesome, I didn't expect a reply, let alone a fix, so fast ^^'

I've got the newer version now and indeed it works again! Very much thx you both!
