### ISSUE TITLE
Dark theme for map

### ISSUE THREAD

**Issue by costales** [rinigus/osmscout-server#379]
Hi,

Is it possible to set a dark theme for the map?

For example, a light theme is calling this:

`http://localhost:8553/v1/mbgl/style?style=osmbright`

But I didn't find a dark theme here:

```
costales@T410:~/Desktop/osmscout-server-master/styles/mapboxgl/styles$ ls
mc-car-en.json  mc-car.json  mc-en.json  mc.json  osmbright-car-en.json  osmbright-car.json  osmbright-en.json  osmbright.json
costales@T410:~/Desktop/osmscout-server-master/styles/mapboxgl/styles$ 
```

Thanks in advance!

**Comment by costales** [comment]
Thank you @rinigus !!

**Comment by rinigus** [comment]
You're welcome!
