### ISSUE TITLE
Can't start bunzip2

### ISSUE THREAD

**Issue by atlochowski** [rinigus/osmscout-server#391]
Just have installed OSM Scout Server from Jolla Store and when I want to download maps I'm getting error.
Error that can't start bunip2

**Comment by atlochowski** [comment]
pkcon search bunzip2 shows that there is no bunzip2 in repo.

**Comment by rinigus** [comment]
Jolla Store OSM Scout Server is VERY outdated. Please use Chum or OpenRepos

**Comment by atlochowski** [comment]
Ok

**Comment by rinigus** [comment]
Closing it here
