### ISSUE TITLE
Can't create map directory because sailjail

### ISSUE THREAD

**Issue by atlochowski** [rinigus/osmscout-server#392]
For next OS release you have to add sailjail permissions to create directory for maps at the first start of app.

**Comment by atlochowski** [comment]
default config gives your app permissions 
"Permissions=Audio;Bluetooth;Camera;Internet;Location;MediaIndexing;Microphone;NFC;RemovableMedia;UserDirs;WebView"

But UserDirs | Access to Documents, Downloads, Music, Pictures, Public and Video directories.

**Comment by rinigus** [comment]
What about creating Maps folder into any location in `~`? What about SD Card? And how are the users who have maps already supposed to use that folder?

**Comment by atlochowski** [comment]
You can create folder into Documents, Downloads, Music, Pictures, Public and Video directories. 
RemovableMedia gives you access to SD card.

It looks like users have to move that folder to Access to Documents, Downloads, Music, Pictures, Public, Video or SD card

**Comment by rinigus** [comment]
As you mention there is an issue with Sailjail and HTTP connection. So, we would have to just disable it for 4.4

**Comment by atlochowski** [comment]
Yeah, for future releases.

**Comment by rinigus** [comment]
Thank you for reporting, it is fixed by disabling Sailjail.
