### ISSUE TITLE
How ofter maps are updated?

### ISSUE THREAD

**Issue by Talkless** [rinigus/osmscout-server#397]
Readme states that "Maps are hosted by Natural Language Processing Centre".

I wonder, how often do they process changes from upstream OSM servers? If I add some changes to the OSM today, how fast I can expect to these changes via osmscout-server? 

Might be useful to have this update rate mentioned in README...

**Comment by rinigus** [comment]
Map updates are irregular and usually take a week or bit more to process the planet. I try to update once in 2-3 months and then upload them to modrana.org. So, in this respect, I can't add any promise to README.

**Comment by Talkless** [comment]
"Maps are updated once in 2-3 months" would be useful enought to note, IMO. No need to "promise" anything, that's understandable.

**Comment by wrenix** [comment]
Looks like the data is not updated for close two years ...

**Comment by rinigus** [comment]
that's correct. I have started update last week on one of the servers available for me and it would take some time - assuming it will go through. As you stated, it hasn't been done for years and maybe some things have changed with the crash at any time possible. 

As for frequency, haven't had time to deal with it and nobody stepped in to handle updates. Let's see if I can do it now periodically.

**Comment by wrenix** [comment]
Maybe it is more usefull to use tiles from other FOSS-Project (like CoMaps/OrganicMaps, OSMAnd(+) or so), if it is to hard for this project to create regualary new update. I am not sure how much work it cost to a compatible with the other formats of map-tiles (regions).

**Comment by wrenix** [comment]
Of sorry I have overseen this issue: https://github.com/rinigus/osmscout-server/issues/453
