### ISSUE TITLE
Default dir on first start is ~/Osm not ~/Documents/Osm

### ISSUE THREAD

**Issue by thigg** [rinigus/osmscout-server#401]
- Start app for the first time
- On Welcome screen click the button to select the default storage folder

IS: ~/Osm is configured

SHOULD: ~/Documents/Osm

**Comment by rinigus** [comment]
No, it was set to ~/Osm by default to avoid mixing it with some other data that user would like to backup. For me, Documents is something that has original content and what should be included into backup scripts. As you want to avoid backing up maps databases, it makes sense to use the default location as done here. 

If this location does not suit some users, it can be changed in settings.

Closing issue.

**Comment by thigg** [comment]
The desciption in the settings says to choose Documents/Osm thats why I mentioned it. Also ~/Osm seems to have permission problems with sailjail

**Comment by thigg** [comment]
Sorry, i dont know what I had in mind, but apperantly its different from what I remember
