### ISSUE TITLE
Test Planetiler for data import

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#403]
Suggested by Gnome Maps devs: https://github.com/onthegomap/planetiler . See also alternatives linked in Planetiler README.

**Comment by jonnius** [comment]
Java would be a challenge for UT, as the system does not provide a JVM. We would need to ship it with the click package.

**Comment by rinigus** [comment]
No, that is what is used for importing maps on the PC/server from OSM formats to the format that is used by OSM Scout Server. So, no need to ship on devices :)

**Comment by jonnius** [comment]
Great! I should have taken a closer look.

**Comment by rinigus** [comment]
Looks to be working well, will probably switch to that. As testing is done, close this issue
