### ISSUE TITLE
Areas for geometry and routing differ

### ISSUE THREAD

**Issue by tpikonen** [rinigus/osmscout-server#408]
I noticed that (at least) the Europe -> Germany -> Hamburg data set (with Default profile) contains geometry and POIs for a large area around Hamburg, but routing and address search work only in a smaller subarea near the actual borders of Hamburg.

It would be less confusing if the offline data sets would have matching map geometry and address data areas.

**Comment by rinigus** [comment]
There are 3 datasets for each region:

- map tiles
- routing tiles
- geocoding data

Out of these, map and routing tiles are made with some given latitude-longitude step and are linked to the region as tiles that overlap with it. Geocoding is, in contrast, following the region border closely. Hence the disparity.

However, for technical reasons, it is going to stay this way. I couldn't make tiles too small either as then web server distributing them would have to start serving lots of small files which has its own overhead. So, size was found as a part of optimization on what's considered reasonable on client and server side.

Closing here, please feel free to continue the discussion even if closed.

**Comment by tpikonen** [comment]
Thanks, I can well understand that there are technical reasons for the different data set borders, but at least in the case of Hamburg, the disparity is huge. The map data covers most of the surrounding state and is at least 5 times larger in diameter than the geocoding area.

I would be interested in learning why either one of these cannot be scaled to be closer to the other (ok, maybe not so interested that I would actually read the source to find out :)).

**Comment by rinigus** [comment]
Well, map tiles are split on zoom level 7 (https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) which makes step in lat/lon significant. For more, see the code.
