### ISSUE TITLE
Bump to latest Valhalla

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#418]

**Comment by rinigus** [comment]
Unfortunately, it requires newer Boost (1.71) than the one we have at SFOS.

**Comment by Thra11** [comment]
What is the process you follow to create the valhalla.json-x.x.x files? Given osmscout-server allows you to specify the valhalla version, I assume you might accept a PR with a working valhalla.json-3.4.0, even if sailfish can't use it yet?

**Comment by rinigus** [comment]
Sure, I will accept corresponding PR.  It is rather manual process where you take default Valhalla config JSON and replace some vars with placeholders, as in https://github.com/rinigus/osmscout-server/blob/master/data/valhalla.json-3.2.1#L161

I usually make a diff with the latest version and then adjust new one accordingly.
