### ISSUE TITLE
Crash on ARM Flatpak while downloading maps

### ISSUE THREAD

**Issue by k8ieone** [rinigus/osmscout-server#423]
Hi, I've run into an issue that I haven't seen reported here before.

OS: Manjaro ARM
DE: phosh
Device: PinePhone
Install method: flatpak

While downloading maps (happens with both an update and a new install), the download works for a while, but then the program crashes.

Here's a log of that happening:
```
flatpak run io.github.rinigus.OSMScoutServer
kf.kirigami: Failed to find a Kirigami platform plugin
file:///usr/lib/qml/org/kde/kirigami.2/private/BannerImage.qml:135:5: QML RowLayout: Binding loop detected for property "height"
file:///usr/lib/qml/org/kde/kirigami.2/private/PrivateActionToolButton.qml:70:5: QML Binding: Binding loop detected for property "value"
DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory
DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory
```

I started writing this issue before I got the logs, now I'm suspecting that Pure Maps might not necessarily be at fault here. Maybe this isn't even related to the download.

**Comment by rinigus** [comment]
Sounds like some memory allocation error. To be sure it is not due to some weird QML effects, please remove caches:

- stop the server
- run `rm -rf ~/.var/app/io.github.rinigus.OSMScoutServer/cache`
- start it again

Try after that. If it didn't help, try to close other apps while downloading.

**Comment by a13xie** [comment]
Thank you for your response, that seems to have fixed the issue. Should I close this?

**Comment by a13xie** [comment]
Oh no, just as I wrote this, it crashed again :/

**Comment by rinigus** [comment]
By searching for "DRM_IOCTL_MODE_CREATE_DUMB PinePhone" it looks like it is some generic bug in system libs. Don't think it can be fixed on OSM Scout Server side. Check out you distribution and alert developers of the issue

**Comment by a13xie** [comment]
Alright, will do. Thanks for your help.

**Comment by rinigus** [comment]
Good luck!

**Comment by a13xie** [comment]
Hi, just a quick update with some good news. This week I'm attempting to use the PinePhone as a daily driver again and as part of the process I tried updating the maps. To my surprise, Scout Server finished the download without a hitch.

It seems like the [upstream problem](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8198) has been fixed.
