### ISSUE TITLE
Lithuania subscribtion has Latvia map too

### ISSUE THREAD

**Issue by Talkless** [rinigus/osmscout-server#426]
On Ubuntu Touch OTA-25 I have subscribed only Lithuania:
![osmscout](https://user-images.githubusercontent.com/292191/234357837-c0ddd845-a2bf-4ee5-80ef-5e2a59d82320.png)

But I can see all the Latvia too. Here's details of capital city Riga:
![riga](https://user-images.githubusercontent.com/292191/234357916-c62d5a8c-d3b0-4a6b-aee7-d22f3b714614.png)

**Comment by rinigus** [comment]
This is due to the compromise between number of files on distribution server and coverage. As a result, we get some maps that are getting regions nearby.

**Comment by Talkless** [comment]
I see. I guess it's not a big issue, 1GB of data is not "too much" in our times.
