### ISSUE TITLE
Can not open the map manager on Volla Phone X (Ubuntu Touch smartphone)

### ISSUE THREAD

**Issue by DNikolaj** [rinigus/osmscout-server#428]
OSM scout does no more provide maps (unknown reason).
I tried to reload maps, but I'm not able to manage to open the map manager. 
Even uninstall and again install leads to a solution.
How, exactly, will the map manager be opened?
Is it possible to load maps via file transfer between PC and the Volla smartphone?

**Comment by rinigus** [comment]
@jonnius could probably comment more on Ubuntu Touch issue. You probably need to specify UT and the map server versions. There shouldn't be any need to transfer files between PC and device.

**Comment by jonnius** [comment]
The map manager is opened by tapping the hamburger menu icon in the top left and then choosing map manager from the menu. What exactly happens when you try that?

Exact UT version (xenial/focal, stable/RC/devel, OTA number) and app version are of interest, too.

**Comment by yazzpro** [comment]
app version  3.0.0. UB touch xenial stable. Hamburger menu does nothing. I have the same result on my device.

**Comment by jonnius** [comment]
Sounds like #404 is a zombie that keeps coming back from time to time. Do you have OTA-23 or later?

**Comment by yazzpro** [comment]
Oh it's my fault. I don't have OTA-23. In fact I had some very old ubtouch version and I couldn't update it. I needed to reinstall it and (this is very important) UNCHECK the "wipe user data" checkbox and only then after reinstalling I could update system. After update it works correctly. Thank you and sorry for confusion.

**Comment by jonnius** [comment]
Good to hear it works now. If you hit an system update issue, please consider reporting it at the ubports bug tracker.

**Comment by yazzpro** [comment]
most probably it would make sense. But I have found this issue while googling for my problems with maps so I thought it might be helpful for next person having this issue. I'll report it to ubports too of course
