### ISSUE TITLE
Incorrect altitude data

### ISSUE THREAD

**Issue by RonnyB74** [rinigus/osmscout-server#429]
I have noticed that some of the altitudes on the map are not correct. Enclosed are two screenshots:

![Bildschirmfoto_20230625_001](https://github.com/rinigus/osmscout-server/assets/65920257/12917b4f-d078-41f9-b710-ef9ae0f38c76)
![Bildschirmfoto_20230629_001](https://github.com/rinigus/osmscout-server/assets/65920257/cadaf9a0-a1fa-4121-8d89-e5c20cf8f3da)

Ronny

**Comment by Karry** [comment]
This bug report belongs to https://github.com/Karry/osmscout-sailfish obviously ;-)

**Comment by Karry** [comment]
Anyway, I changed elevation internal format from unsign integer to sign one recently. It is possible that I made some mistake in the code hanling old database format... Do you using recent map databases?

**Comment by RonnyB74** [comment]
The map shown here (Europe/Alps) is from 13.05.2023.

**Comment by Karry** [comment]
Thank you for the report. I was able to reproduce this issue finally. It will be fixed in the next release: https://github.com/Karry/libosmscout/commit/fa239ccc693f60ab8910b718ce8de247c4416f63

**Comment by Karry** [comment]
New version with the fix was released on OpenRepos.

**Comment by RonnyB74** [comment]
Sorry, I must have mixed things up when I posted the report.

The error has been corrected, thank you for that!

**Comment by rinigus** [comment]
Closing here :)
