### ISSUE TITLE
Support for newer versions of libosmscout

### ISSUE THREAD

**Issue by syyyr** [rinigus/osmscout-server#436]
Hi,
I'm trying to use _osmscout-server_ as a simple tile server, that uses _libosmscout_ as a backend. I don't need any kind of routing, searching, or anything, just a web server, that gives tiles under some URL (ideally in the  "/x/y/z.png" format).

Building _osmscout-server_ with the latest version of _libosmscout_ gives a lot of errors. For example, a lot of headers were moved around in _libosmscout_ and some APIs were changed also. Are newer versions of _libosmscout_ not supported? If so, which version should I use to build _osmscout-server_ with support for _libosmscout_?

**Comment by rinigus** [comment]
Hi!

libosmscout support has been discontinued from version 2.0.0 (Mar 29 2021). Already then it was using old libosmscout version and it couldn't keep up with their development. As nobody wanted to take over maintenance of that backend, I dropped it.

**Comment by syyyr** [comment]
Thanks for the quick answer.

One more question: Do you think that using osmscout-server with mapnik is a good alternative to libosmscout for my usecase (that is, offline tile generation and a tile webserver?

**Comment by rinigus** [comment]
I wonder whether using some regular Mapnik tile server would be better. Or even use Mapbox GL based backend to generate and serve raster tiles. That would allow you to import the data as you want and not depend on my updates.

**Comment by syyyr** [comment]
Do you have any recommendation for a regular Mapnik tile server? Looking [here](https://wiki.openstreetmap.org/wiki/Tile_servers) and [here](https://switch2osm.org/serving-tiles/), I can see that the defacto go-to tile server is the mod_tile thingy, which requires Apache. I'm not 100% against using Apache, but if there's something more lightweight, I'd go for that. On the other hand, serving tiles seems like a not-so-easy task.

**Comment by syyyr** [comment]
Or perhaps I should use the docker container solution here? https://switch2osm.org/serving-tiles/using-a-docker-container/

Docker is probably fine for me, however, I am a little concerned about the size warning (30 GB for a small import). When using libosmscout, the imported database was around 300 MB for my usecase (just country borders and details of a few cities).

**Comment by syyyr** [comment]
Thank you very much, you've been a big help.
