### ISSUE TITLE
System Theme Not Detected

### ISSUE THREAD

**Issue by DicePenguin** [rinigus/osmscout-server#442]
The app doesn't detect system theme at all. Also should this be an option in the Settings tab?

Device: Pinephone (community edition)
System: PostmarketOS 23.12
Environment: Phosh 0.33.0

**Comment by rinigus** [comment]
That should be done on the system level, not by the app. Note that the server is using Kirigami/KDE and the theme support is provided by those. As I am using other OS, I cannot help you with it. Check how to make KDE/Kirigami to follow Phosh theme or setup their theme accordingly. Closing it here as it is not app-related. Unless you have noticed that the server is somehow ignoring KDE/Kirigami settings - then reopen
