### ISSUE TITLE
Sailfish os 4.6.0.11 missing libprotobuf.so29

### ISSUE THREAD

**Issue by smatkovi** [rinigus/osmscout-server#447]
When installed from chum under sailfish OS 4.6.0.11 it complains about libprotobuf.so29, that it is missing.

**Comment by rinigus** [comment]
How did you install it for 4.6? As far as I can see, Chum 4.6 repos are not ready. So, as a result, the server cannot be used either

**Comment by smatkovi** [comment]
i set the version on chum to 4.5. i also tried to compile it on sfos 4.6.0.12 first on the phone, then with sfossdk updated through ssu re 4.6.0.11; zypper up; and i get the following errors on both: `In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/spirit/home/qi/string/symbols.hpp:30,
                 from /usr/include/boost/spirit/home/qi/string.hpp:15,
                 from /usr/include/boost/spirit/home/qi.hpp:28,
                 from /usr/include/boost/spirit/include/qi.hpp:16,
                 from include/mapnik/css_color_grammar.hpp:34,
                 from include/mapnik/image_filter_grammar.hpp:28,
                 from src/image_filter_grammar.cpp:23:
/usr/include/boost/spirit/include/phoenix.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix.hpp> instead.’
   12 | BOOST_HEADER_DEPRECATED("<boost/phoenix.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/phoenix/stl.hpp:14,
                 from /usr/include/boost/phoenix/phoenix.hpp:19,
                 from /usr/include/boost/phoenix.hpp:11,
                 from /usr/include/boost/spirit/include/phoenix.hpp:14,
                 from include/mapnik/image_filter_grammar_impl.hpp:29,
                 from src/image_filter_grammar.cpp:24:
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:16:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’; did you mean ‘uarg1’?
   16 |         BOOST_PP_LOCAL_MACRO(1)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:19:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   19 |         BOOST_PP_LOCAL_MACRO(2)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:22:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   22 |         BOOST_PP_LOCAL_MACRO(3)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:25:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   25 |         BOOST_PP_LOCAL_MACRO(4)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:28:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   28 |         BOOST_PP_LOCAL_MACRO(5)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:31:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   31 |         BOOST_PP_LOCAL_MACRO(6)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:34:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   34 |         BOOST_PP_LOCAL_MACRO(7)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:37:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   37 |         BOOST_PP_LOCAL_MACRO(8)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:40:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’
   40 |         BOOST_PP_LOCAL_MACRO(9)
      |         ^~~~~~~~~~~~~~~~~~~~
/usr/include/boost/preprocessor/iteration/detail/limits/local_256.hpp:43:9: error: ‘arg1’ is not a member of ‘boost::phoenix::placeholders’; did you mean ‘uarg10’?
   43 |         BOOST_PP_LOCAL_MACRO(10)
      |         ^~~~~~~~~~~~~~~~~~~~
scons: *** [src/image_filter_grammar.os] Error 1
scons: building terminated because of errors.
make: *** [Makefile:57: mapnik] Error 2
`

**Comment by smatkovi** [comment]
on 4.6.0.13, with chum also supporting 4.6.0.13 it still complains about this missing library

**Comment by rinigus** [comment]
Do you still have this issue? When using the version from Chum?
