### ISSUE TITLE
Routing broken recently in UK - maybe bad valhalla datasets?

### ISSUE THREAD

**Issue by mtbu** [rinigus/osmscout-server#450]
The routing seems to be broken recently (at least in north-east England), I think it's since I updated the map data earlier this month, but I'm not sure exactly when it started.
I'm using UBports and this affects both Pure Maps and uNav. If I set Pure Maps to use Mixed profile with an online provider such as Stadia Maps I get the routes I would expect, but using OSM Scout Server (valhalla) I now get crazy routes with lots of turns and illogical paths, for example instead of 3 miles of mostly straight line I might get 21 miles with some main roads, some zigzagging through residential blocks, even some overlapping loops.
The issue seems to affect multiple routing types (Car, Foot, Bicycle).

I've tried unsubscribing and re-subscribing to the data or downloading England instead of Great Britain, but I get the same problems.

Currently I have 'Europe / Great Britain', with:
- Geocoder-NLP 03/10/2024
- Address parsing country-specific support 20/05/2018
- Mapbox GL country-specific support 02/10/2024
- Valhalla 03/10/2024

I can't tell if there's a way to download the older data instead to test with this?

**Comment by mtbu** [comment]
Here's a sample between two random locations just far enough away from me to not show my current home location in the screenshots :)
First screenshot is the whole route and 2nd is when I zoom in on a bad bit.
(If I route with Stadia Maps it does the same route in 7 miles, almost a straight line)

![screenshot20241022_224436747](https://github.com/user-attachments/assets/3c5153c1-f0cc-4e5a-af3b-050783e097c9)
![screenshot20241022_224454266](https://github.com/user-attachments/assets/5bcd77ac-7ae2-4c8f-abc0-c77d05f84caa)

**Comment by rinigus** [comment]
there is no way to download older data, unfortunately. To reproduce it, would you mind to tell bit more:
- which dataset you used (in terms of country/territory). Under GB/England there is a lot of options
- maybe you could share coordinates for start/end of this case?

Just in case, check settings in router inside Pure Maps. I presume those are for car?

**Comment by mtbu** [comment]
Thanks for getting back to me!
I just downloaded the whole "Europe / Great Britain" dataset.
That route was Lat 54.8929, Lon -1.6871, to Lat 54.8149, Lon -1.76092

Pure Maps routing settings as per screenshot. Unselecting "Prefer shorter route" made the route a bit shorter but still very indirect.

![screenshot20241023_231727477](https://github.com/user-attachments/assets/450077c3-207f-4fe7-b4fe-580faa737a3c)

Here are the log messages in OSM Scout Server:

![screenshot20241023_231930122](https://github.com/user-attachments/assets/896c7556-7330-4270-9043-de1766541590)

**Comment by rinigus** [comment]
I get a decent route between those two points. Check what is the version for Valhalla in your build (in OSM Scout Server, choose About and scroll to the bottom). Is it 3.4.x?

**Comment by mtbu** [comment]
That's it! I was on OSM Scout Server 3.0.0 from Feb 2023 (since that was the one in the UBports Open Store) so an old Valhalla version (it didn't say exactly which one).
Manually compiling OSM Scout Server from master on this repo has fixed the issue.
Thanks!

**Comment by jonnius** [comment]
@rinigus, maybe we should tag a little release to get the updated valhalla version to Ubuntu Touch? I have never released 3.1.0, but that one also had valhalla 3.0.9 still.

**Comment by rinigus** [comment]
@jonnius , here you go: https://github.com/rinigus/osmscout-server/releases/tag/3.1.5 :)

**Comment by jonnius** [comment]
Thanks! Is the update so significant, that it got 5 increments on patch level? :D

**Comment by rinigus** [comment]
It actually would have warranted new release, but its invisible for users (having new map import procedure)

**Comment by mtbu** [comment]
I've tried installing the open-store version now instead of my compiled one,  it's just downloading v3.0.0 not the v3.1.5. I've now checked the open-store.io website and the Download button only shows v3.0.0 releases?

**Comment by jonnius** [comment]
I just uploaded 3.1.5. Also check the note on service failure issues on updates that you can find in the [description](https://open-store.io/app/osmscout-server.jonnius).
