### ISSUE TITLE
replace start and target with description during routing

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#51]
if target and start were given by search, we can specify strings corresponding to them while routing. has to support libosmscout and geocoder-nlp search

**Comment by rinigus** [comment]
Its possible to translate Start and Target now (after https://github.com/rinigus/osmscout-server/commit/c818fd3e91f848b42c696beac4c57e8d09811452), but address would be more appropriate

**Comment by Caballlero** [comment]
good! 
- Rinigus can you explain to me why words are being displayed when they should be hidden? I'm confused.

**Comment by rinigus** [comment]
That's a good point, I guess I can skip "Start" and "Target" if there is no additional info regarding them (like address)

**Comment by Caballlero** [comment]
ok , so now is ready to translate the string > can you notify a carmen to fix ?

**Comment by rinigus** [comment]
@Caballlero: I would prefer not to ping translators - they do it from the free time and its better not to bug them too much :) . So far, she has been fast in updating the translation, let's wait a bit...

**Comment by rinigus** [comment]
and the corresponding PR has been just merged :) 

https://github.com/rinigus/osmscout-server/pull/60

Now I just have to change the code and replace Start/Target with the addresses

**Comment by Caballlero** [comment]
#thank you

**Comment by rinigus** [comment]
Fixed with the latest commit
