### ISSUE TITLE
Cannot change maps folder

### ISSUE THREAD

**Issue by mase76** [rinigus/osmscout-server#62]
Hi!
I was not able to change the maps folder within the app. I could not accept the chosen path.
I had to edit the config file.

**Comment by rinigus** [comment]
Thank you for report! 

Would you mind to be more specific? Namely, was GUI able to show you the folder or GUI was not able to open it in file browser? 

At present, folder selection assumes that there is a specific file in that folder. I assume that you wanted to open libsomscout map data folder, right? Would you mind to send which files do you have there (`ls `)?

**Comment by mase76** [comment]
I wanted to change the map data folder to ~/maps. I created that folder
before. I was able to browse to that folder. But I found no way to
accept the folder. I still had no data in it. If there must be a
specific file
in there, the user should be prompted to move all files to the new
location. Otherwise the folder selection
has no function.

**Comment by Karry** [comment]
Hmm, try to use full path: "/home/nemo/maps/", I am not sure if Qt interprets tilde character as home directory as shell does...

**Comment by mase76** [comment]
I did not use ~. I entered the folder with the filemanager. My question is, how to accept the folder entered with the filemanager? Swiping back cancels the selection.

**Comment by rinigus** [comment]
The file manager dialog that selects a directory is looking for specific file in that directory. Its maybe not the best design, but at that moment I was looking for as simple solution for the user as possible. As a limitation, you cannot select a folder without a map. So, you have to get the map first and select second.

As you point out, its not written in such form (or I don't remember about it from the top of my head) and should be at least communicated to the users. 

When I get to your question: no, you cannot now select an empty directory with the current file manager.

Things will change in future versions. I am planning to incorporate the map downloads and then the user would have to do as you wished - select the directory where to put maps data first. I'll probably just make the file manager as usual, as a dialog with Cancel|Accept on the top.

For now, please live with this limitation...

**Comment by rinigus** [comment]
fixed in the latest development branch. fix will be part of the next release
