### ISSUE TITLE
split larger downloads into parts

### ISSUE THREAD

**Issue by rinigus** [rinigus/osmscout-server#87]
To ensure that the downloads can withstand interruptions. 

For that, make a new type "BZ2Split" for FileDownloader. Split BZ2 archive into chunks and download a chunk in a time. As soon as chunk is downloaded, feed it to bunzip2 and proceed with the next chunk.

On server, split all files that are larger than 15MB (or 10MB) into chunks (like area.dat.bz2.0, ...). In provided JSON, introduce new flag that indicates how data is stored (plain, bz2, bz2split).

**Comment by Karry** [comment]
Hi Rinigus. Such splitting should not be needed. http (and majority of the servers) supports get request with initial offset. It is used for restoring downloads. But I am not sure how to do it with qt...

**Comment by rinigus** [comment]
Hi Lukas, you are spot on!!! That's much more elegant way of doing it. Something is like it is described at http://docs.aws.amazon.com/AmazonS3/latest/dev/GettingObjectsUsingAPIs.html . I will look into how to make these Range requests for Qt and feed to bunzip2 only when the range has been fully downloaded. Thank you!

**Comment by rinigus** [comment]
In the current implementation, network errors lead to restart of the downloads. There are two caches involved to avoid issues with some garbage data that occurs just before error triggering. What's left to do is:

* implement timeout for http requests (if no data is received, the manager could wait forever). seems that I have to use timer for that

* hook download counter so that user would see data when arrived and not when dumped from the safe cache to the file.

**Comment by rinigus** [comment]
Downloading is much more robust now. Closing
