### ISSUE TITLE
>> Letter of thanks <<

### ISSUE THREAD

**Issue by Caballlero** [rinigus/osmscout-server#99]
i just thank you for your big work, i am fan of  osmscout-server and I follow step step the evolution of this app + _ +

   YOU ARE THE BEST OF THIS.         >       TRUE JOLLA DEVELOPER @rinigus

**Comment by rinigus** [comment]
@Caballlero , thank you very much! I enjoy working on it and there are lots of others helping as they can. We are progressing nicely and quite fast, let's keep working on it!

Cheers and I am closing this as an issue :)
